### ISSUE TITLE
Migration plugin does not detect "path":"full" mapping

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch-migration#47] opened 2016-01-13 20:47 UTC
Older Logstash templates include a "path":"full" directive in the mapping under their "geoip" definition.  This is no longer supported by Elasticsearch, and if the existing Logstash template includes "path":"full", LS will silently fail to create its daily index and nothing will be ingested after upgrade.  The migration tool should flag this for correction so the user can update Logstash and correct the existing template.

**Comment by schmichael** [comment] 2016-02-17 23:02
The issue is that template mappings (and perhaps templates altogether) aren't checked. This bit me with a different invalid template mapping.

**Comment by clintongormley** [comment] 2016-04-27 13:55
Yes, not much we can do about index templates.  Closing

**Closed as completed by clintongormley** 2016-04-27 13:55 UTC

**Comment by fpeterschmitt** [comment] 2016-12-14 10:02
Just to add a solution for anyone coming to this issue:

 * Get the `logtash` mapping and remove the `path: full` "parameter"
 * Update the `logstash` template in ES so the `path: full` of `geoip` is absent.
 * Force logstash to use a custom template instead of it's own template.

```
$ curl http://localhost:9200/_template/logstash?pretty=true > logstash.template.json
# edit logstash.template.json so you get a template as defined by this documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

# now update the template
$ cat logstash.template.json |curl -XPUT http://localhost:9200/_template/logstash -d '@-'
{"acknowledged":true}
```

I've not done the logstash part because I don't need to do it.

Now you can upgrade your indices :)
